/**
 * ============================================================================
 * Torafirma Design System — Layout & Shell Barrel Export
 * ============================================================================
 *
 * Central barrel export for all Layout & Shell components.
 * Import components from this module:
 *
 *   import { AppShell, TopCommandBar, LeftNavRail } from './layout-shell';
 * ============================================================================
 */

export { default as types } from "./types";
export * from "./types";

export { default as AppShell } from "./AppShell";
export type { AppShellProps } from "./AppShell";
export { default as TopCommandBar } from "./TopCommandBar";
export type { TopCommandBarProps } from "./TopCommandBar";
export { default as TopCommandBarCompact } from "./TopCommandBarCompact";
export type { TopCommandBarCompactProps } from "./TopCommandBarCompact";
export { default as LeftNavRail } from "./LeftNavRail";
export type { LeftNavRailProps } from "./LeftNavRail";
export { default as LeftNavRailCollapsed } from "./LeftNavRailCollapsed";
export type { LeftNavRailCollapsedProps } from "./LeftNavRailCollapsed";
export { default as LeftNavRailExpanded } from "./LeftNavRailExpanded";
export type { LeftNavRailExpandedProps } from "./LeftNavRailExpanded";
export { default as RightInspector } from "./RightInspector";
export type { RightInspectorProps } from "./RightInspector";
export { default as RightInspectorResizable } from "./RightInspectorResizable";
export type { RightInspectorResizableProps } from "./RightInspectorResizable";
export { default as RightInspectorTabbed } from "./RightInspectorTabbed";
export type { RightInspectorTabbedProps } from "./RightInspectorTabbed";
export { default as BottomTraceConsole } from "./BottomTraceConsole";
export type { BottomTraceConsoleProps } from "./BottomTraceConsole";
export { default as BottomTraceConsoleMinimized } from "./BottomTraceConsoleMinimized";
export type { BottomTraceConsoleMinimizedProps } from "./BottomTraceConsoleMinimized";
export { default as BottomPanel } from "./BottomPanel";
export type { BottomPanelProps } from "./BottomPanel";
export { default as BottomPanelResizable } from "./BottomPanelResizable";
export type { BottomPanelResizableProps } from "./BottomPanelResizable";
export { default as MainContentArea } from "./MainContentArea";
export type { MainContentAreaProps } from "./MainContentArea";
export { default as MainContentAreaSplit } from "./MainContentAreaSplit";
export type { MainContentAreaSplitProps } from "./MainContentAreaSplit";
export { default as WorkspaceArea } from "./WorkspaceArea";
export type { WorkspaceAreaProps } from "./WorkspaceArea";
export { default as WorkspaceTabBar } from "./WorkspaceTabBar";
export type { WorkspaceTabBarProps } from "./WorkspaceTabBar";
export { default as WorkspaceTab } from "./WorkspaceTab";
export type { WorkspaceTabProps } from "./WorkspaceTab";
export { default as SplitPane } from "./SplitPane";
export type { SplitPaneProps } from "./SplitPane";
export { default as SplitPaneHandle } from "./SplitPaneHandle";
export type { SplitPaneHandleProps } from "./SplitPaneHandle";
export { default as DockPanel } from "./DockPanel";
export type { DockPanelProps } from "./DockPanel";
export { default as DockPanelHeader } from "./DockPanelHeader";
export type { DockPanelHeaderProps } from "./DockPanelHeader";
export { default as DockPanelTab } from "./DockPanelTab";
export type { DockPanelTabProps } from "./DockPanelTab";
export { default as DockZone } from "./DockZone";
export type { DockZoneProps } from "./DockZone";
export { default as Panel } from "./Panel";
export type { PanelProps } from "./Panel";
export { default as PanelHeader } from "./PanelHeader";
export type { PanelHeaderProps } from "./PanelHeader";
export { default as PanelContent } from "./PanelContent";
export type { PanelContentProps } from "./PanelContent";
export { default as PanelFooter } from "./PanelFooter";
export type { PanelFooterProps } from "./PanelFooter";
export { default as PanelResizable } from "./PanelResizable";
export type { PanelResizableProps } from "./PanelResizable";
export { default as PanelCollapsible } from "./PanelCollapsible";
export type { PanelCollapsibleProps } from "./PanelCollapsible";
export { default as PanelDraggable } from "./PanelDraggable";
export type { PanelDraggableProps } from "./PanelDraggable";
export { default as PanelFloating } from "./PanelFloating";
export type { PanelFloatingProps } from "./PanelFloating";
export { default as Toolbar } from "./Toolbar";
export type { ToolbarProps } from "./Toolbar";
export { default as ToolbarGroup } from "./ToolbarGroup";
export type { ToolbarGroupProps } from "./ToolbarGroup";
export { default as ToolbarSeparator } from "./ToolbarSeparator";
export type { ToolbarSeparatorProps } from "./ToolbarSeparator";
export { default as ToolbarSpacer } from "./ToolbarSpacer";
export type { ToolbarSpacerProps } from "./ToolbarSpacer";
export { default as BreadcrumbBar } from "./BreadcrumbBar";
export type { BreadcrumbBarProps } from "./BreadcrumbBar";
export { default as BreadcrumbItem } from "./BreadcrumbItem";
export type { BreadcrumbItemProps } from "./BreadcrumbItem";
export { default as BreadcrumbSeparator } from "./BreadcrumbSeparator";
export type { BreadcrumbSeparatorProps } from "./BreadcrumbSeparator";
export { default as StatusBar } from "./StatusBar";
export type { StatusBarProps } from "./StatusBar";
export { default as StatusBarSection } from "./StatusBarSection";
export type { StatusBarSectionProps } from "./StatusBarSection";
export { default as StatusBarDivider } from "./StatusBarDivider";
export type { StatusBarDividerProps } from "./StatusBarDivider";
export { default as TitleBar } from "./TitleBar";
export type { TitleBarProps } from "./TitleBar";
export { default as TitleBarControls } from "./TitleBarControls";
export type { TitleBarControlsProps } from "./TitleBarControls";
export { default as Sidebar } from "./Sidebar";
export type { SidebarProps } from "./Sidebar";
export { default as SidebarHeader } from "./SidebarHeader";
export type { SidebarHeaderProps } from "./SidebarHeader";
export { default as SidebarSection } from "./SidebarSection";
export type { SidebarSectionProps } from "./SidebarSection";
export { default as SidebarItem } from "./SidebarItem";
export type { SidebarItemProps } from "./SidebarItem";
export { default as SidebarItemGroup } from "./SidebarItemGroup";
export type { SidebarItemGroupProps } from "./SidebarItemGroup";
export { default as SidebarFooter } from "./SidebarFooter";
export type { SidebarFooterProps } from "./SidebarFooter";
export { default as HeaderBar } from "./HeaderBar";
export type { HeaderBarProps } from "./HeaderBar";
export { default as HeaderBarTitle } from "./HeaderBarTitle";
export type { HeaderBarTitleProps } from "./HeaderBarTitle";
export { default as HeaderBarActions } from "./HeaderBarActions";
export type { HeaderBarActionsProps } from "./HeaderBarActions";
export { default as HeaderBarBreadcrumb } from "./HeaderBarBreadcrumb";
export type { HeaderBarBreadcrumbProps } from "./HeaderBarBreadcrumb";
export { default as FooterBar } from "./FooterBar";
export type { FooterBarProps } from "./FooterBar";
export { default as ContentHeader } from "./ContentHeader";
export type { ContentHeaderProps } from "./ContentHeader";
export { default as ContentFooter } from "./ContentFooter";
export type { ContentFooterProps } from "./ContentFooter";
export { default as PageLayout } from "./PageLayout";
export type { PageLayoutProps } from "./PageLayout";
export { default as PageLayoutWithSidebar } from "./PageLayoutWithSidebar";
export type { PageLayoutWithSidebarProps } from "./PageLayoutWithSidebar";
export { default as PageLayoutFullWidth } from "./PageLayoutFullWidth";
export type { PageLayoutFullWidthProps } from "./PageLayoutFullWidth";
export { default as PageLayoutCentered } from "./PageLayoutCentered";
export type { PageLayoutCenteredProps } from "./PageLayoutCentered";
export { default as GridLayout } from "./GridLayout";
export type { GridLayoutProps } from "./GridLayout";
export { default as GridLayoutItem } from "./GridLayoutItem";
export type { GridLayoutItemProps } from "./GridLayoutItem";
export { default as FlexLayout } from "./FlexLayout";
export type { FlexLayoutProps } from "./FlexLayout";
export { default as FlexLayoutItem } from "./FlexLayoutItem";
export type { FlexLayoutItemProps } from "./FlexLayoutItem";
export { default as ResizableContainer } from "./ResizableContainer";
export type { ResizableContainerProps } from "./ResizableContainer";
export { default as ResizableHandle } from "./ResizableHandle";
export type { ResizableHandleProps } from "./ResizableHandle";
export { default as ScrollablePanel } from "./ScrollablePanel";
export type { ScrollablePanelProps } from "./ScrollablePanel";
export { default as ScrollableArea } from "./ScrollableArea";
export type { ScrollableAreaProps } from "./ScrollableArea";
export { default as StickyHeader } from "./StickyHeader";
export type { StickyHeaderProps } from "./StickyHeader";
export { default as StickyFooter } from "./StickyFooter";
export type { StickyFooterProps } from "./StickyFooter";
export { default as OverlayLayout } from "./OverlayLayout";
export type { OverlayLayoutProps } from "./OverlayLayout";
export { default as ModalLayout } from "./ModalLayout";
export type { ModalLayoutProps } from "./ModalLayout";
export { default as DrawerLayout } from "./DrawerLayout";
export type { DrawerLayoutProps } from "./DrawerLayout";
export { default as DrawerHeader } from "./DrawerHeader";
export type { DrawerHeaderProps } from "./DrawerHeader";
export { default as DrawerContent } from "./DrawerContent";
export type { DrawerContentProps } from "./DrawerContent";
export { default as DrawerFooter } from "./DrawerFooter";
export type { DrawerFooterProps } from "./DrawerFooter";
export { default as FloatingLayout } from "./FloatingLayout";
export type { FloatingLayoutProps } from "./FloatingLayout";
export { default as FloatingWindow } from "./FloatingWindow";
export type { FloatingWindowProps } from "./FloatingWindow";
export { default as WindowTitleBar } from "./WindowTitleBar";
export type { WindowTitleBarProps } from "./WindowTitleBar";
export { default as TabLayout } from "./TabLayout";
export type { TabLayoutProps } from "./TabLayout";
export { default as TabList } from "./TabList";
export type { TabListProps } from "./TabList";
export { default as TabPanel } from "./TabPanel";
export type { TabPanelProps } from "./TabPanel";
export { default as TabItem } from "./TabItem";
export type { TabItemProps } from "./TabItem";
export { default as AccordionLayout } from "./AccordionLayout";
export type { AccordionLayoutProps } from "./AccordionLayout";
export { default as AccordionItem } from "./AccordionItem";
export type { AccordionItemProps } from "./AccordionItem";
export { default as AccordionHeader } from "./AccordionHeader";
export type { AccordionHeaderProps } from "./AccordionHeader";
export { default as AccordionContent } from "./AccordionContent";
export type { AccordionContentProps } from "./AccordionContent";
export { default as CardLayout } from "./CardLayout";
export type { CardLayoutProps } from "./CardLayout";
export { default as Card } from "./Card";
export type { CardProps } from "./Card";
export { default as CardHeader } from "./CardHeader";
export type { CardHeaderProps } from "./CardHeader";
export { default as CardContent } from "./CardContent";
export type { CardContentProps } from "./CardContent";
export { default as CardFooter } from "./CardFooter";
export type { CardFooterProps } from "./CardFooter";
export { default as CardActions } from "./CardActions";
export type { CardActionsProps } from "./CardActions";
export { default as MasonryLayout } from "./MasonryLayout";
export type { MasonryLayoutProps } from "./MasonryLayout";
export { default as ListLayout } from "./ListLayout";
export type { ListLayoutProps } from "./ListLayout";
export { default as ListItem } from "./ListItem";
export type { ListItemProps } from "./ListItem";
export { default as ListItemAction } from "./ListItemAction";
export type { ListItemActionProps } from "./ListItemAction";
export { default as DetailLayout } from "./DetailLayout";
export type { DetailLayoutProps } from "./DetailLayout";
export { default as MasterPane } from "./MasterPane";
export type { MasterPaneProps } from "./MasterPane";
export { default as DetailPane } from "./DetailPane";
export type { DetailPaneProps } from "./DetailPane";
export { default as DashboardLayout } from "./DashboardLayout";
export type { DashboardLayoutProps } from "./DashboardLayout";
export { default as DashboardWidget } from "./DashboardWidget";
export type { DashboardWidgetProps } from "./DashboardWidget";
export { default as DashboardWidgetHeader } from "./DashboardWidgetHeader";
export type { DashboardWidgetHeaderProps } from "./DashboardWidgetHeader";
export { default as DashboardGrid } from "./DashboardGrid";
export type { DashboardGridProps } from "./DashboardGrid";
export { default as CommandCockpitShell } from "./CommandCockpitShell";
export type { CommandCockpitShellProps } from "./CommandCockpitShell";
export { default as BuilderStudioShell } from "./BuilderStudioShell";
export type { BuilderStudioShellProps } from "./BuilderStudioShell";
export { default as AnalysisDashboardShell } from "./AnalysisDashboardShell";
export type { AnalysisDashboardShellProps } from "./AnalysisDashboardShell";
export { default as DataWorkspaceShell } from "./DataWorkspaceShell";
export type { DataWorkspaceShellProps } from "./DataWorkspaceShell";
export { default as OperationsCenterShell } from "./OperationsCenterShell";
export type { OperationsCenterShellProps } from "./OperationsCenterShell";
export { default as FieldConsoleShell } from "./FieldConsoleShell";
export type { FieldConsoleShellProps } from "./FieldConsoleShell";
export { default as AIStudioShell } from "./AIStudioShell";
export type { AIStudioShellProps } from "./AIStudioShell";
export { default as ForgeIDEShell } from "./ForgeIDEShell";
export type { ForgeIDEShellProps } from "./ForgeIDEShell";
export { default as TraceConsoleShell } from "./TraceConsoleShell";
export type { TraceConsoleShellProps } from "./TraceConsoleShell";
export { default as GovernanceShell } from "./GovernanceShell";
export type { GovernanceShellProps } from "./GovernanceShell";
// ---------------------------------------------------------------------------
// Motion & Animation Wrappers
// ---------------------------------------------------------------------------
export * from './motion';

// ---------------------------------------------------------------------------
// Error Boundaries
// ---------------------------------------------------------------------------
export * from './errors';
